"use strict";
/*
    app.js, main Angular application script
    define your module and controllers here
*/

var tasksUrl = 'https://api.parse.com/1/classes/tasks';

angular.module('RatingApp', [])
    .config(function($httpProvider) {
        //Parse required two extra headers sent with every HTTP request: X-Parse-Application-Id, X-Parse-REST-API-Key
        //the first needs to be set to your application's ID value
        //the second needs to be set to your application's REST API key
        //both of these are generated by Parse when you create your application via their web site
        //the following lines will add these as default headers so that they are sent with every
        //HTTP request we make in this application
        $httpProvider.defaults.headers.common['X-Parse-Application-Id'] = 'Eaxfl95zoQfv8deM8rkfIlHOOiOcZ4sABVfzUDpA';
        $httpProvider.defaults.headers.common['X-Parse-REST-API-Key'] = 'hRRs7VK5ZsHR4lHAQZdG43D2d0fpLo7Oqe08JK17';
    })